//! Shared schema primitives: content digests, wall-clock timestamps and the
//! identifiers threaded through decisions, rules and policy revisions.

use serde::{Deserialize, Serialize};

/// 32-byte content digest. blake3 by convention; changing the hash function
/// is a breaking schema change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Digest(pub [u8; 32]);

/// Wall-clock timestamp in milliseconds since the Unix epoch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Timestamp(pub u64);

/// Decision identifier (ULID), generated by the requester or backfilled by
/// the framework; threads through verdicts, receipts and audit records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct DecisionId(pub ulid::Ulid);

/// Compile-time rule identifier, referenced by reasons and audit records.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RuleId(pub String);

/// Active policy revision: anti-rollback monotonic epoch plus bundle hash.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PolicyRevision {
    /// Monotonically increasing `policyEpoch` from the bundle manifest.
    pub epoch: u64,
    /// Content hash (merkle root) of the active bundle.
    pub bundle_hash: Digest,
}
