//! Decision request snapshot: `DecisionRequest` and `InterventionPoint`
//! (§3.3). Each intervention point defines a deterministic input snapshot and
//! the set of effects it may return (e.g. `OsEventAsync` never yields MODIFY).

use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::attribute::Attribute;
use crate::event::EventEnvelope;
use crate::primitives::DecisionId;
use crate::subject::SubjectRef;

/// Enforcement mode hint carried by the request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EnforceMode {
    /// Rules only produce audit obligations; nothing is blocked.
    Monitor,
    /// Rules are fully enforced.
    Enforce,
}

/// Interception points with ACS-like snapshot semantics (§3.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InterventionPoint {
    /// Session start.
    SessionStart,
    /// Session end.
    SessionEnd,
    /// Before an LLM call.
    LlmCallPre,
    /// After an LLM call.
    LlmCallPost,
    /// Before a tool call.
    ToolCallPre,
    /// After a tool call.
    ToolCallPost,
    /// Skill activation.
    SkillActivation,
    /// Skill upgrade.
    SkillUpgrade,
    /// Credential use.
    CredentialUse,
    /// Post-hoc adjudication of interface A events; drives tightening only,
    /// never blocks the syscall and never returns MODIFY.
    OsEventAsync,
    /// Out-of-band CLI control plane.
    ControlPlane,
}

/// Adjudication request (§3.3): the canonical snapshot handed to the PDP.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DecisionRequest {
    /// Request schema version; currently 1.
    pub schema_version: u16,
    /// Decision id, generated by the requester or backfilled by the
    /// framework; threads through the whole chain.
    pub decision_id: DecisionId,
    /// Interception point being adjudicated.
    pub intervention: InterventionPoint,
    /// Decision subject.
    pub subject: SubjectRef,
    /// Triggering event.
    pub event: EventEnvelope,
    /// Session-scoped attributes valid for this decision only, never stored
    /// (OpenFGA contextual-tuples style); assurance is fixed at P1 (§7.3).
    pub inline_context: Vec<Attribute>,
    /// Enforcement mode hint; defaults to the bundle configuration.
    pub mode_hint: Option<EnforceMode>,
    /// Requester latency budget; exceeding it falls back to the intervention
    /// point's default fail semantics.
    pub deadline: Option<Duration>,
}
