//! Production daemon admission and Runtime wiring.

use std::collections::BTreeMap;
use std::path::Component;

use super::*;
use crate::checkpoint::CheckpointDriver;

#[derive(Debug, Clone, Copy, ValueEnum)]
enum ServeCapabilityProfile {
    TaskOnlyV1,
    WorkspaceCheckpointV1,
}

impl ServeCapabilityProfile {
    fn profile(self) -> GatewayCapabilityProfile {
        match self {
            Self::TaskOnlyV1 => GatewayCapabilityProfileId::TaskOnlyV1.profile(),
            Self::WorkspaceCheckpointV1 => {
                GatewayCapabilityProfileId::WorkspaceCheckpointV1.profile()
            }
        }
    }
}

#[derive(Debug, Clone, Args)]
pub(super) struct ServeArgs {
    /// Absolute Unix socket path; defaults below the user runtime directory.
    #[arg(long, value_name = "PATH")]
    pub(super) socket: Option<PathBuf>,
    /// Absolute private SQLite database path; defaults below user state.
    #[arg(long, value_name = "PATH")]
    pub(super) database: Option<PathBuf>,
    /// Closed capability profile admitted for this daemon instance.
    #[arg(long, value_enum, default_value_t = ServeCapabilityProfile::TaskOnlyV1)]
    capability_profile: ServeCapabilityProfile,
    /// Absolute ws-ckpt socket required by workspace-checkpoint-v1.
    #[arg(long, value_name = "PATH")]
    checkpoint_socket: Option<PathBuf>,
    /// Absolute append-only security audit log for governed effects.
    #[arg(long, value_name = "PATH")]
    security_audit: Option<PathBuf>,
    /// Provision this installation identity on first start; generated by default.
    #[arg(long, value_name = "INSTALLATION_ID")]
    pub(super) installation_id: Option<String>,
    /// Absolute installed cosh-core executable for the brokered Runtime.
    #[arg(long, value_name = "PATH")]
    core_executable: Option<PathBuf>,
    /// Existing workspace directory admitted for every Task in this daemon.
    #[arg(long, default_value = ".")]
    pub(super) workspace: PathBuf,
    /// Live systemd service unit whose cgroup owns this production daemon.
    #[arg(long, value_name = "UNIT")]
    pub(super) systemd_unit: Option<String>,
    /// Presentation format for startup and stable errors.
    #[arg(long, value_enum, default_value_t = Output::Human)]
    pub(super) output: Output,
}

pub(super) fn serve(args: ServeArgs, reporter: &Reporter) -> Result<u8, CliError> {
    let installation_id = args
        .installation_id
        .map(InstallationId::parse)
        .transpose()
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    let capability_profile = args.capability_profile.profile();
    if capability_profile.id() == GatewayCapabilityProfileId::TaskOnlyV1
        && (args.checkpoint_socket.is_some() || args.security_audit.is_some())
    {
        return Err(CliError::Profile(
            "checkpoint configuration requires workspace-checkpoint-v1".to_owned(),
        ));
    }
    let target = capability_profile.governed_target();
    let configured_workspace = if args.workspace.is_absolute() {
        args.workspace.clone()
    } else {
        std::env::current_dir()
            .map_err(|error| CliError::Profile(error.to_string()))?
            .join(&args.workspace)
    };
    let configured_workspace = normalize_absolute_workspace(&configured_workspace)?;
    let workspace = TrustedWorkspaceResolver::new(target.clone(), &configured_workspace)
        .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))?;
    if let Some(unit) = args.systemd_unit.as_deref() {
        LinuxSystemdContainmentVerifier::validate_unit(unit)
            .map_err(|error| CliError::Containment(error.to_string()))?;
    }
    let containment_unit = args.systemd_unit.as_deref().ok_or_else(|| {
        CliError::Containment("production serve requires --systemd-unit".to_owned())
    })?;
    let environment = std::env::vars_os().collect::<BTreeMap<_, _>>();
    let resolved_core_profile = InstalledBrokeredCoreRuntimePortFactory::resolve(
        required_absolute(
            args.core_executable.as_ref(),
            "brokered cosh-core executable",
        )?,
        environment,
    )
    .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))?;
    let containment = LinuxSystemdContainmentVerifier::new()
        .verify(containment_unit)
        .map_err(|error| CliError::Containment(error.to_string()))?;
    let runtime = serve_runtime_selector(capability_profile)?;
    let socket_path = daemon_socket_path(args.socket.as_ref())?;
    let database_path = daemon_database_path(args.database.as_ref())?;
    SqliteTaskStore::prepare_path(&database_path)
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    let mut checkpoint_driver = match capability_profile.id() {
        GatewayCapabilityProfileId::TaskOnlyV1 => {
            cosh_gateway::capability::SealedCapabilityProviderRegistry::task_only(
                capability_profile,
            )
            .map_err(|error| CliError::Profile(error.to_string()))?;
            None
        }
        GatewayCapabilityProfileId::WorkspaceCheckpointV1 => {
            let checkpoint_socket =
                required_absolute(args.checkpoint_socket.as_ref(), "ws-ckpt daemon socket")?;
            let audit_path = match args.security_audit {
                Some(path) => require_absolute(&path, "security audit")?,
                None => database_path.with_extension("security-audit.jsonl"),
            };
            if audit_conflicts_database(&audit_path, &database_path) {
                return Err(CliError::Profile(
                    "security audit path must be distinct from Gateway database files".to_owned(),
                ));
            }
            Some(
                CheckpointDriver::admit(
                    capability_profile,
                    checkpoint_socket,
                    &configured_workspace,
                    audit_path,
                    nix::unistd::Uid::effective().as_raw(),
                )
                .map_err(|error| CliError::Profile(error.to_string()))?,
            )
        }
    };
    let config = GatewayDaemonConfig {
        socket_path,
        database_path,
        installation_id,
        capability_profile,
        workspace: workspace.workspace_ref().clone(),
        runtime,
    };
    let interrupted = install_interrupt_handler()?;
    let mut daemon =
        GatewayDaemon::bind(config).map_err(|error| CliError::Daemon(error.to_string()))?;
    let actor_resolver = LocalOsActorResolver::new(
        daemon.installation_id().clone(),
        nix::unistd::Uid::effective().as_raw(),
    );
    let worker_id = BoundedOpaque::new(RuntimeInstanceId::new().to_string())
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    let port_factory = InstalledBrokeredCoreRuntimePortFactory::from_resolved(
        daemon.installation_id().clone(),
        actor_resolver,
        workspace,
        resolved_core_profile,
    )
    .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))?;
    if let Some(driver) = checkpoint_driver.take() {
        daemon
            .attach_brokered_scheduler(
                containment,
                worker_id,
                Box::new(ScheduledAgentRuntimeFactory::new(port_factory)),
                Box::new(driver),
            )
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    } else {
        daemon
            .attach_task_only_scheduler(
                containment,
                worker_id,
                Box::new(ScheduledAgentRuntimeFactory::new(port_factory)),
            )
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    }
    reporter.event("daemon_ready", json!({}))?;
    daemon
        .serve_until(interrupted.as_ref())
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    Ok(0)
}

pub(super) fn normalize_absolute_workspace(path: &Path) -> Result<PathBuf, CliError> {
    if !path.is_absolute() {
        return Err(CliError::Profile(
            "workspace path must resolve to an absolute path".to_owned(),
        ));
    }
    let mut normalized = PathBuf::from("/");
    for component in path.components() {
        match component {
            Component::RootDir | Component::CurDir => {}
            Component::Normal(part) => normalized.push(part),
            Component::ParentDir => {
                if !normalized.pop() {
                    return Err(CliError::Profile(
                        "workspace path must not traverse above root".to_owned(),
                    ));
                }
            }
            Component::Prefix(_) => {
                return Err(CliError::Profile(
                    "workspace path uses an unsupported platform prefix".to_owned(),
                ));
            }
        }
    }
    Ok(normalized)
}

fn audit_conflicts_database(audit_path: &Path, database_path: &Path) -> bool {
    if audit_path == database_path {
        return true;
    }
    ["-wal", "-shm"]
        .into_iter()
        .map(|suffix| {
            let mut companion = database_path.as_os_str().to_os_string();
            companion.push(suffix);
            PathBuf::from(companion)
        })
        .any(|companion| audit_path == companion)
}

fn serve_runtime_selector(profile: GatewayCapabilityProfile) -> Result<RuntimeSelector, CliError> {
    let profile_name = match profile.id() {
        GatewayCapabilityProfileId::TaskOnlyV1 => GATEWAY_BROKERED_CORE_RUNTIME_PROFILE,
        GatewayCapabilityProfileId::WorkspaceCheckpointV1 => {
            GATEWAY_CHECKPOINT_CORE_RUNTIME_PROFILE
        }
    };
    Ok(RuntimeSelector {
        runtime: BoundedName::new("core").map_err(|error| CliError::Profile(error.to_string()))?,
        profile: Some(
            BoundedName::new(profile_name).map_err(|error| CliError::Profile(error.to_string()))?,
        ),
    })
}

fn required_absolute(path: Option<&PathBuf>, label: &str) -> Result<PathBuf, CliError> {
    let path = path.ok_or_else(|| CliError::Daemon(format!("{label} path is required")))?;
    require_absolute(path, label)
}
