//! Built-in YAML rule packs for the L1 rule engine.
//!
//! The rule-pack YAML files live in this crate's `rules/` directory and
//! are embedded at compile time, so the engine carries its rule set with
//! no runtime file lookup.

use serde::Deserialize;

use crate::error::ScannerError;
use crate::result::Severity;

/// Built-in injection rules.
const INJECTION_YAML: &str = include_str!("../rules/injection.yaml");
/// Built-in jailbreak rules.
const JAILBREAK_YAML: &str = include_str!("../rules/jailbreak.yaml");
/// ATR prompt-injection pack (generated by sync_atr — see rules/atr/UPSTREAM.toml).
const ATR_PROMPT_INJECTION_YAML: &str = include_str!("../rules/atr/prompt_injection.yaml");
/// ATR agent-manipulation pack (generated by sync_atr).
const ATR_AGENT_MANIPULATION_YAML: &str = include_str!("../rules/atr/agent_manipulation.yaml");
/// ATR context-exfiltration pack (generated by sync_atr).
const ATR_CONTEXT_EXFILTRATION_YAML: &str = include_str!("../rules/atr/context_exfiltration.yaml");

/// Provenance metadata carried by every rule pack.
#[derive(Debug, Clone, Deserialize)]
pub struct PackMeta {
    /// Pack identifier, e.g. "builtin-injection" / "atr-prompt-injection".
    pub name: String,
    /// Rule origin: "builtin" or an external source name like "atr".
    pub source: String,
    /// Own version for builtin packs; upstream tag for converted packs.
    pub version: String,
    /// License of the rules in this pack (attribution requirement).
    pub license: String,
    /// Upstream repository URL for converted packs.
    #[serde(default)]
    pub upstream: Option<String>,
    /// Converter name for generated packs — presence means "do not edit".
    #[serde(default)]
    pub generated_by: Option<String>,
}

/// Embedded acceptance samples: TPs must fire the owning rule, TNs must not.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct TestCases {
    #[serde(default)]
    pub true_positives: Vec<String>,
    #[serde(default)]
    pub true_negatives: Vec<String>,
}

/// A single detection rule used by the L1 rule engine.
#[derive(Debug, Clone, Deserialize)]
pub struct Rule {
    /// Unique identifier, e.g. "INJ-001" or upstream "ATR-2026-00001".
    pub id: String,
    /// Human-readable rule name.
    pub name: String,
    /// Threat-type namespace value, passed through to `ThreatDetail`.
    pub category: String,
    #[serde(default)]
    pub subcategory: String,
    pub severity: Severity,
    /// Regex patterns.
    #[serde(default)]
    pub patterns: Vec<String>,
    #[serde(default)]
    pub description: String,
    /// Upstream rule location for converted rules.
    #[serde(default)]
    pub url: Option<String>,
    /// OWASP / MITRE ATLAS / CVE cross-references.
    #[serde(default)]
    pub references: Vec<String>,
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// True: '.' does not match newlines for this rule.
    #[serde(default)]
    pub single_line: bool,
    #[serde(default)]
    pub test_cases: TestCases,
}

fn default_true() -> bool {
    true
}

/// A self-describing rule pack: provenance header plus rule list.
#[derive(Debug, Clone, Deserialize)]
pub struct Pack {
    pub pack: PackMeta,
    pub rules: Vec<Rule>,
}

/// Parse a YAML rule-pack document.
///
/// # Errors
///
/// Returns [`ScannerError::Config`] when the YAML is malformed or a rule is
/// missing a mandatory field.
fn parse_pack(yaml: &str, origin: &str) -> Result<Pack, ScannerError> {
    serde_yaml::from_str(yaml)
        .map_err(|exc| ScannerError::Config(format!("Invalid rule pack {origin}: {exc}")))
}

/// Load all built-in rule packs.
///
/// # Errors
///
/// Returns [`ScannerError::Config`] when an embedded YAML file is
/// malformed — indicates a packaging bug, not a runtime condition.
pub fn builtin_packs() -> Result<Vec<Pack>, ScannerError> {
    Ok(vec![
        parse_pack(INJECTION_YAML, "injection.yaml")?,
        parse_pack(JAILBREAK_YAML, "jailbreak.yaml")?,
        parse_pack(ATR_PROMPT_INJECTION_YAML, "atr/prompt_injection.yaml")?,
        parse_pack(ATR_AGENT_MANIPULATION_YAML, "atr/agent_manipulation.yaml")?,
        parse_pack(
            ATR_CONTEXT_EXFILTRATION_YAML,
            "atr/context_exfiltration.yaml",
        )?,
    ])
}

/// Flatten all built-in packs into a single rule list for the L1 engine.
///
/// # Errors
///
/// Propagates [`ScannerError::Config`] from [`builtin_packs`].
pub fn builtin_rules() -> Result<Vec<Rule>, ScannerError> {
    Ok(builtin_packs()?
        .into_iter()
        .flat_map(|pack| pack.rules)
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_rules_parse() {
        let rules = builtin_rules().expect("built-in YAML must parse");
        assert!(!rules.is_empty());
        // Every rule carries the mandatory fields.
        for rule in &rules {
            assert!(!rule.id.is_empty());
            assert!(
                !rule.patterns.is_empty(),
                "rule {} has no patterns",
                rule.id
            );
        }
        // Spot-check a known rule from each file.
        assert!(rules.iter().any(|r| r.id == "INJ-001"));
        assert!(rules.iter().any(|r| r.id == "JB-001"));
    }

    #[test]
    fn rule_ids_are_unique_across_builtin_files() {
        // The L1 engine collects at most one hit per rule by iterating the
        // set once, which only yields per-rule uniqueness if the ids
        // themselves are unique.  Lock that invariant here.
        let rules = builtin_rules().unwrap();
        let mut seen: std::collections::HashSet<&str> = std::collections::HashSet::new();
        let duplicates: Vec<&str> = rules
            .iter()
            .filter(|rule| !seen.insert(rule.id.as_str()))
            .map(|rule| rule.id.as_str())
            .collect();
        assert!(duplicates.is_empty(), "duplicate rule ids: {duplicates:?}");
    }

    #[test]
    fn single_line_flag_is_parsed() {
        let rules = builtin_rules().unwrap();
        // INJ-015 is the only rule using single_line: true (multi-line
        // false-positive fix); make sure the flag survives parsing.
        let single_line: Vec<_> = rules.iter().filter(|r| r.single_line).collect();
        assert!(!single_line.is_empty());
    }

    #[test]
    fn packs_carry_provenance_metadata() {
        let packs = builtin_packs().expect("built-in packs must parse");
        assert_eq!(packs.len(), 5);
        for pack in &packs {
            assert!(!pack.pack.version.is_empty());
            match pack.pack.source.as_str() {
                "builtin" => {
                    assert_eq!(pack.pack.license, "Apache-2.0");
                    assert!(pack.pack.generated_by.is_none());
                }
                "atr" => {
                    assert_eq!(pack.pack.license, "MIT");
                    assert_eq!(pack.pack.generated_by.as_deref(), Some("sync_atr"));
                }
                other => panic!("unexpected pack source {other:?}"),
            }
        }
        assert_eq!(
            packs.iter().filter(|p| p.pack.source == "builtin").count(),
            2
        );
        assert_eq!(packs.iter().filter(|p| p.pack.source == "atr").count(), 3);
        assert!(packs.iter().any(|p| p.pack.name == "builtin-injection"));
        assert!(packs.iter().any(|p| p.pack.name == "builtin-jailbreak"));
    }

    #[test]
    fn optional_v2_rule_fields_parse() {
        let yaml = r#"
pack:
  name: t
  source: atr
  version: "3.5.11"
  license: MIT
  upstream: https://example.com/repo
  generated_by: sync_atr
rules:
  - id: ATR-2026-99999
    name: "T"
    category: prompt_injection
    severity: high
    patterns: ['(?i)x']
    url: https://example.com/rule.yaml
    references: ["LLM01:2025"]
    test_cases:
      true_positives: ["x marks the spot"]
      true_negatives: ["nothing here"]
"#;
        let pack = parse_pack(yaml, "inline").expect("inline v2 pack must parse");
        let rule = &pack.rules[0];
        assert_eq!(rule.subcategory, "");
        assert_eq!(rule.url.as_deref(), Some("https://example.com/rule.yaml"));
        assert_eq!(rule.references, vec!["LLM01:2025"]);
        assert_eq!(rule.test_cases.true_positives.len(), 1);
        assert_eq!(rule.test_cases.true_negatives.len(), 1);
        assert_eq!(pack.pack.generated_by.as_deref(), Some("sync_atr"));
    }
}
